name: Docker Image Tagged

on:
  release:
    types: [created]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nickp60/ezclermont:${GITHUB_REF_NAME}
    - name: Push the Image
      run: docker push nickp60/ezclermont:${GITHUB_REF_NAME}
